# Generated by Django 3.0.7 on 2020-06-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_nome', models.CharField(max_length=100)),
                ('host_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('host_porta', models.PositiveIntegerField(max_length=5)),
                ('host_observacoes', models.TextField(max_length=500)),
            ],
        ),
    ]
