# Generated by Django 3.0.7 on 2020-06-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='host_porta',
            field=models.PositiveIntegerField(),
        ),
    ]
