# Generated by Django 3.0.7 on 2020-06-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_auto_20200617_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_status',
            field=models.BooleanField(default=True),
        ),
    ]
