# Generated by Django 3.0.7 on 2020-06-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0004_host_host_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_porta',
            field=models.PositiveIntegerField(default=161),
        ),
    ]
