# Generated by Django 3.0.7 on 2020-06-19 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0006_auto_20200617_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_nome', models.CharField(max_length=100)),
                ('item_oid', models.CharField(max_length=100)),
                ('item_tipoInformacao', models.CharField(choices=[('NI', 'Numérico(Inteiro)'), ('ND', 'Numérico(Decimal)'), ('CH', 'Caracter'), ('LG', 'Log'), ('TX', 'Texto')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_nome', models.CharField(max_length=100)),
                ('template_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.Itens')),
            ],
        ),
    ]
