# Generated by Django 3.0.7 on 2020-06-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0008_auto_20200619_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='template_item',
        ),
        migrations.AddField(
            model_name='template',
            name='template_item',
            field=models.ManyToManyField(to='hosts.Item'),
        ),
    ]
