# Generated by Django 3.0.7 on 2020-06-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0009_auto_20200619_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_template',
            field=models.ManyToManyField(to='hosts.Template'),
        ),
    ]
