# Generated by Django 3.0.7 on 2020-06-30 00:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0011_auto_20200619_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='host_nomeTabela',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
