# Generated by Django 3.0.7 on 2020-06-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0015_auto_20200629_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_nomeTabela',
            field=models.CharField(max_length=100),
        ),
    ]
