# Generated by Django 3.0.7 on 2020-07-01 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0016_auto_20200629_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='host_nomeTabela',
            new_name='host_nomeTabela_snmpGet',
        ),
    ]
