# Generated by Django 3.1 on 2020-09-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0017_auto_20200630_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_intervaloAtualizacaoUn',
            field=models.CharField(choices=[('seconds', 'Segundos'), ('minutes', 'Minutos'), ('hours', 'Horas'), ('days', 'Dias'), ('months', 'Meses'), ('years', 'Anos')], default=('minutes', 'Minutos'), max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_tempoArmazenamentoDadosUn',
            field=models.CharField(choices=[('seconds', 'Segundos'), ('minutes', 'Minutos'), ('hours', 'Horas'), ('days', 'Dias'), ('months', 'Meses'), ('years', 'Anos')], default=('days', 'Dias'), max_length=100),
        ),
    ]
