# Generated by Django 3.1 on 2021-01-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0018_auto_20200831_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_tempoArmazenamentoDadosUn',
            field=models.CharField(choices=[('minutes', 'Minutos'), ('hours', 'Horas'), ('days', 'Dias'), ('months', 'Meses'), ('years', 'Anos')], default=('days', 'Dias'), max_length=100),
        ),
    ]
