# Generated by Django 3.1 on 2021-09-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0021_auto_20210314_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_expressaoConversao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
