# Generated by Django 3.1 on 2021-09-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0022_item_item_expressaoconversao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_expressaoConversao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
